// Generated by CoffeeScript 1.6.3
/*

  youtubeManager

  2013 (c) Andrey Popp <8mayday@gmail.com>
*/


(function() {
  var YoutubeSound, youtubeManager;

  YoutubeSound = (function() {
    var extractIdRe;

    extractIdRe = /v=([^&]+)/;

    function YoutubeSound(options) {
      var videoId,
        _this = this;
      this.options = options;
      this.buffered = void 0;
      this.bytesLoaded = void 0;
      this.bytesTotal = 1;
      this.isBuffering = void 0;
      this.connected = void 0;
      this.duration = void 0;
      this.durationEstimate = void 0;
      this.isHTML5 = false;
      this.loaded = false;
      this.muted = false;
      this.paused = false;
      this.playState = void 0;
      this.position = 0;
      this.readyState = 0;
      this.element = document.createElement('div');
      this.element.setAttribute('id', options.id);
      this.element.setAttribute('class', 'ym-container');
      document.body.appendChild(this.element);
      this._autoPlay = this.options.autoPlay;
      this._whileplaying = void 0;
      this._whileloading = void 0;
      this._previousState = void 0;
      videoId = options.youtubeVideoId || extractIdRe.exec(options.url)[1];
      if (videoId == null) {
        throw new Error("cannot extract videoId from URL: " + options.url);
      }
      this.videoId = videoId;
      this.player = new YT.Player(options.id, {
        height: options.height,
        width: options.width,
        videoId: videoId,
        events: {
          onReady: function() {
            return _this.onReady();
          },
          onStateChange: function() {
            return _this.onStateChange();
          }
        },
        playerVars: {
          controls: '0',
          enablejsapi: '1',
          modestbranding: '1',
          showinfo: '0',
          playerapiid: options.id
        }
      });
    }

    YoutubeSound.prototype.onReady = function() {
      this.duration = this.durationEstimate = this.player.getDuration() * 1000;
      if (this._autoPlay) {
        this.play();
      }
      if (this.options.volume) {
        this.setVolume(this.options.volume);
      }
      return this._startLoadingPoller();
    };

    YoutubeSound.prototype.onStateChange = function() {
      var state;
      state = this.player.getPlayerState();
      if (state === -1) {
        this.duration = this.durationEstimate = this.player.getDuration() * 1000;
      }
      if (state === YT.PlayerState.PLAYING) {
        this.duration = this.durationEstimate = this.player.getDuration() * 1000;
        this._startPlayingPoller();
        this.paused = false;
        if (this.options.onplay) {
          this.options.onplay.apply(this);
        }
        if (this.options.onresume && this._previousState === YT.PlayerState.PAUSED) {
          this.options.onresume.apply(this);
        }
      } else if (state === YT.PlayerState.PAUSED) {
        this._stopPlayingPoller();
        this.paused = true;
        if (this.options.onpause) {
          this.options.onpause.apply(this);
        }
      } else if (state === YT.PlayerState.ENDED) {
        this.paused = false;
        this._stopPlayingPoller();
        if (this.options.onfinish) {
          this.options.onfinish.apply(this);
        }
      }
      return this._previousState = state;
    };

    YoutubeSound.prototype._startPlayingPoller = function() {
      var _this = this;
      return this._whileplaying = setInterval((function() {
        return _this._updatePosition();
      }), this.options.pollingInterval || 500);
    };

    YoutubeSound.prototype._stopPlayingPoller = function() {
      if (!this._whileplaying) {
        return;
      }
      clearInterval(this._whileplaying);
      return this._whileplaying = void 0;
    };

    YoutubeSound.prototype._updatePosition = function() {
      this.position = this.player.getCurrentTime() * 1000;
      if (this.options.whileplaying) {
        return this.options.whileplaying.apply(this);
      }
    };

    YoutubeSound.prototype._startLoadingPoller = function() {
      var _this = this;
      return this._whileloading = setInterval((function() {
        return _this._updateLoading();
      }), this.options.pollingInterval || 500);
    };

    YoutubeSound.prototype._stopLoadingPoller = function() {
      if (!this._whileloading) {
        return;
      }
      clearInterval(this._whileloading);
      return this._whileloading = void 0;
    };

    YoutubeSound.prototype._updateLoading = function() {
      this.bytesLoaded = this.player.getVideoLoadedFraction();
      if (this.bytesLoaded === 1) {
        this.loaded = true;
        if (this.options.onload) {
          this.options.onload.apply(this);
        }
        this._stopLoadingPoller();
      }
      if (this.options.whileloading) {
        return this.options.whileloading.apply(this);
      }
    };

    YoutubeSound.prototype.destruct = function() {
      return this.player.destroy();
    };

    YoutubeSound.prototype.load = function() {};

    YoutubeSound.prototype.clearOnPosition = function() {};

    YoutubeSound.prototype.onPosition = function() {};

    YoutubeSound.prototype.mute = function() {
      this.muted = true;
      return this.player.mute();
    };

    YoutubeSound.prototype.pause = function() {
      if (this.player.pauseVideo != null) {
        return this.player.pauseVideo();
      } else {
        return this._autoPlay = false;
      }
    };

    YoutubeSound.prototype.play = function() {
      if (this.player.playVideo != null) {
        return this.player.playVideo();
      } else {
        return this._autoPlay = true;
      }
    };

    YoutubeSound.prototype.resume = function() {
      return this.play();
    };

    YoutubeSound.prototype.setPan = function() {};

    YoutubeSound.prototype.setPosition = function(ms) {
      return this.player.seekTo(ms / 1000);
    };

    YoutubeSound.prototype.setVolume = function(v) {
      return this.player.setVolume(v);
    };

    YoutubeSound.prototype.stop = function() {
      if (this.player.stopVideo != null) {
        this.player.seekTo(0);
        this.player.stopVideo();
        this._stopPlayingPoller();
        this._stopLoadingPoller();
        return this.position = 0;
      } else {
        return this._autoPlay = false;
      }
    };

    YoutubeSound.prototype.toggleMute = function() {
      if (this.player.isMuted()) {
        return this.unmute();
      } else {
        return this.mute();
      }
    };

    YoutubeSound.prototype.togglePause = function() {
      if (this.player.getPlayerState() === YT.PlayerState.PLAYING) {
        return this.pause();
      } else {
        return this.play();
      }
    };

    YoutubeSound.prototype.unload = function() {};

    YoutubeSound.prototype.unmute = function() {
      this.muted = false;
      return this.player.unMute();
    };

    return YoutubeSound;

  })();

  youtubeManager = {
    createSound: function(options) {
      return new YoutubeSound(options);
    },
    setup: function(options) {
      var oldCallback;
      if (options == null) {
        options = {};
      }
      if (window.onYouTubeIframeAPIReady != null) {
        oldCallback = window.onYouTubeIframeAPIReady;
      }
      window.onYouTubeIframeAPIReady = function() {
        if (options.onready) {
          options.onready();
        }
        if (oldCallback) {
          return oldCallback();
        }
      };
      return this._injectScript();
    },
    _injectScript: function() {
      var firstScriptTag, tag;
      tag = document.createElement('script');
      if (window.location.host === 'localhost') {
        tag.src = "http://www.youtube.com/player_api";
      } else {
        tag.src = "//www.youtube.com/player_api";
      }
      firstScriptTag = document.getElementsByTagName('script')[0];
      return firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
    }
  };

  if ((typeof define !== "undefined" && define !== null ? define.amd : void 0) != null) {
    define(youtubeManager);
  }

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    module.exports = youtubeManager;
  }

}).call(this);
